### ISSUE TITLE
git clone git@github.com:raspberrypi-ui/scratch-gui.git is giving permission denied error

### ISSUE THREAD

**Issue by abhisek-mishra** [raspberrypi-ui/scratch-gui#2]
pi@raspberrypi:~/scratch-gui $ git clone git@github.com:raspberrypi-ui/scratch-gui.git
Cloning into 'scratch-gui'...
Warning: Permanently added the RSA host key for IP address '13.234.176.102' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please let me know what I am missing. Thanks a lot for your help, I am running this on raspberry pi4.

**Comment by spl237** [comment]
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh
