### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by MonsieurNaexec** [raspberrypi-ui/scratch-gui#5]
Hello,
I'm planning to write a custom extension for some hardware I've got with the Pi, so scratch-gui seems to be a good way to start.
The problem is: I just can't get to build the project.
I cloned the repository and used the `build.sh` script, but when it starts the build in `~/scratch-desktop/node_modules/scratch-gui`, it fails with the following output:
```
93% after chunk asset optimization SourceMapDevToolPlugin lib.min.js generate SourceMap
<--- Last few GCs --->

[26919:0x4503148]   289004 ms: Scavenge 199.6 (208.5) -> 198.6 (209.0) MB, 5.5 / 0.0 ms  (average mu = 0.931, current mu = 0.853) allocation failure 
[26919:0x4503148]   289063 ms: Scavenge 200.2 (209.0) -> 198.9 (209.3) MB, 21.8 / 0.0 ms  (average mu = 0.931, current mu = 0.853) allocation failure 
[26919:0x4503148]   289108 ms: Scavenge 200.7 (209.3) -> 199.1 (209.3) MB, 5.3 / 0.0 ms  (average mu = 0.931, current mu = 0.853) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! scratch-gui@0.1.0 build: `npm run clean && webpack --colors --bail`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the scratch-gui@0.1.0 build script.
```

I tried to set `NODE_OPTIONS=--max-old-space-size=4096` (globally) but it didn't solve the issue.
I'm on a fresh install of the latest version of Raspberry Pi OS.
Also, I gave my pi 2Gb of swap, but the build seems to fail even before all the RAM is used (without using any swap).
I tried to build it on a Ubuntu machine with more than 10Gb of RAM and the script worked, but I had de same issue when trying to `npm run dist`

I think I'm not the only one facing this issue, and I really don't know how to solve it. Could you tell me what I did wrong? Maybe I didn't understand perfectly how to build the project?

**Comment by spl237** [comment]
The problem with building this project is that it pulls in the latest version of hundreds of node.js modules, and any one of them could be causing the problem.

Your best bet is to use the MIT GitHub where they originally wrote and maintain scratch-gui, rather than here, as this is just a snapshot that worked at a particular time and is almost certainly now out of date, whereas their version should be updated to the current state of said node.js modules.

Have a look at https://github.com/LLK/scratch-desktop
